#!/bin/bash

if [ ! -e /dev/kvm ]; then
    echo "⚠️ KVM module not found. The emulator will run in software mode."
    export NO_KVM=1
fi

if [ ! command -v docker &> /dev/null ]; then
    echo "❌ Docker is not installed."
    echo "Please install Docker before running this script."
    exit 1
fi

# check if the $HOME/.Xauthority file exists
# if it does, we set the XAUTHORITY variable to it
if [ -f "$HOME/.Xauthority" ]; then
    export XAUTHORITY="$HOME/.Xauthority"
else
    echo "⚠️ Xauthority file not found. Setting it as /dev/null applications may not be able to connect to the X server."
fi

# get the arch and set the tag accordingly
ARCH=$(uname -m)

if [ "$ARCH" == "x86_64" ]; then
    export TAG="latest"
elif [ "$ARCH" == "aarch64" ]; then
    export TAG="arm64-v2"
else
    echo "❌ Unsupported architecture: $ARCH"
    echo "Please run this script on an x86_64 or aarch64 machine."
    exit 1
fi

# make to sure that we have ~/.pem folder
if [ ! -d ~/.pem ]; then
    mkdir ~/.pem
fi

# make the xhost accessible to the container
xhost + >/dev/null 2>&1 || true

# check if we are passing an argument
# if so, the argument need to be a valid file path
if [ $# -gt 2 ]; then
    echo "❌ Too many arguments."
    echo "Usage: $0 [absolute-image-path] [arm64|amd64]"
    exit 69
fi

if [ $# -ge 1 ]; then
    # Check if the provided path is a file and is absolute
    if [ ! -f "$1" ] || [[ "$1" != /* ]]; then
        echo "❌ Invalid file path: $1"
        echo "Please provide a valid absolute file path."
        exit 69
    fi

    # check if there is a second argument
    # if so, it should be arm64 or amd64
    if [ $# -eq 2 ]; then
        if [ "$2" != "arm64" ] && [ "$2" != "amd64" ]; then
            echo "❌ Invalid architecture: $2"
            echo "Please provide a valid architecture (arm64 or amd64)."
            exit 69
        fi

        # if the second argument is valid, we set the PHOBOS_OVERRIDE_ARCH
        if [ "$2" == "arm64" ]; then
            export PHOBOS_OVERRIDE_ARCH="aarch64"
        else
            export PHOBOS_OVERRIDE_ARCH="x86_64"
        fi
    fi

    export PHOBOS_LOCAL_IMG_PATH="$1"
    export PHOBOS_LOCAL_FIRMWARE_PATH="$(dirname "$PHOBOS_LOCAL_IMG_PATH")"
else
    # if no argument is passed, we use the default path
    export PHOBOS_LOCAL_IMG_PATH="/opt/phobos-emulator-manager"
    export PHOBOS_LOCAL_FIRMWARE_PATH="$PHOBOS_LOCAL_IMG_PATH"
fi

if [ -z "$WSL_DISTRO_NAME" ]; then

    if [ -z "$NO_KVM" ]; then
        docker compose \
            -f /opt/phobos-emulator-manager/docker-compose.yml \
            run -it --rm phobos-emulator-manager
    else
         docker compose \
            -f /opt/phobos-emulator-manager/docker-compose.yml \
            run -it --rm phobos-emulator-manager-no-kvm
    fi
else

    if [ -z "$NO_KVM" ]; then
        docker compose \
            -f /opt/phobos-emulator-manager/docker-compose.yml \
            run -it --rm phobos-emulator-manager-wsl
    else
         docker compose \
            -f /opt/phobos-emulator-manager/docker-compose.yml \
            run -it --rm phobos-emulator-manager-no-kvm-wsl
    fi
fi

# remove the xhost access
xhost - >/dev/null 2>&1 || true
