#!/bin/bash

if [ ! -e /dev/kvm ]; then
    echo "⚠️ KVM module not found. The emulator will run in software mode."
    export NO_KVM=1
fi

if [ ! command -v docker &> /dev/null ]; then
    echo "❌ Docker is not installed."
    echo "Please install Docker before running this script."
    exit 1
fi

# make the xhost accessible to the container
xhost + || true

if [ -z "$WSL_DISTRO_NAME" ]; then

    if [ -z "$NO_KVM" ]; then
        docker compose \
            -f /opt/torizon-emulator-manager/docker-compose.yml \
            run --rm torizon-emulator-manager
    else
         docker compose \
            -f /opt/torizon-emulator-manager/docker-compose.yml \
            run --rm torizon-emulator-manager-no-kvm
    fi
else

    if [ -z "$NO_KVM" ]; then
        docker compose \
            -f /opt/torizon-emulator-manager/docker-compose.yml \
            run --rm torizon-emulator-manager-wsl
    else
         docker compose \
            -f /opt/torizon-emulator-manager/docker-compose.yml \
            run --rm torizon-emulator-manager-no-kvm-wsl
    fi
fi

# remove the xhost access
xhost - || true
