version: "3.9"

services:
  emulator:
    image: pergamos/phobos:0.0.0.3
    privileged: true
    network_mode: host
    init: false
    environment:
      - DISPLAY=${DISPLAY:-:1}
      - INSTANCES=${INSTANCES:-1}
      - STORAGE=${STORAGE:-8}
      - RAM=${RAM:-4}
      - NO_KVM=${NO_KVM}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - dhcp

  dhcp:
    image: pergamos/phobos:0.0.0.3
    command:
      - dhcp
    privileged: true
    network_mode: host
    init: false
