services:
  emulator:
    image: pergamos/phobos:latest
    privileged: true
    network_mode: host
    init: false
    environment:
      - DISPLAY=${DISPLAY:-:1}
      - INSTANCES=${INSTANCES:-1}
      - STORAGE=${STORAGE:-8}
      - RAM=${RAM:-4}
      - NO_KVM=${NO_KVM:-""}
      - USER_VM_NAME=${USER_VM_NAME:-""}
    volumes:
      - /tmp:/tmp
      - /root/.pem/:/root/.pem
    depends_on:
      - dhcp
      - tpm2

  emulator-debug:
    image: pergamos/phobos:latest
    privileged: true
    network_mode: host
    init: false
    environment:
      - DISPLAY=${DISPLAY:-:1}
      - INSTANCES=${INSTANCES:-1}
      - STORAGE=${STORAGE:-8}
      - RAM=${RAM:-4}
      - NO_KVM=${NO_KVM:-""}
    volumes:
      - /tmp:/tmp
      - ${PHOBOS_LOCAL_IMG_PATH:-/dev/null}:/phobos.img
    depends_on:
      - dhcp
      - tpm2

  dhcp:
    image: pergamos/phobos:latest
    command:
      - dhcp
    privileged: true
    network_mode: host
    init: false

  tpm2:
    image: pergamos/phobos:latest
    command:
      - tpm2
    privileged: true
    network_mode: host
    init: false
    volumes:
      - /tmp:/tmp

  image-download:
    image: pergamos/phobos:latest
    command:
      - image-download
    privileged: true
    network_mode: host
    init: false
    volumes:
      - /tmp:/tmp
      - ${PHOBOS_LOCAL_IMG_PATH:-/dev/null}:/phobos.img
